### ISSUE TITLE
No Screenshoot

### ISSUE THREAD

**Issue by Lawendt** [tobiasbu/raytracer#2]
You said coming soon almost a year ago.

**Comment by tobiasbu** [comment]
Choices ¯\_(ツ)_/¯ 

I promise that I will post on this week

**Comment by tobiasbu** [comment]
Greetings @Lawendt.
Thanks for you issue report.

I updated recently the README.md with the screenshots.
Also, you can check the **[raytracer project page](http://tobiasbu.github.io/portfolio/raytracer/)** for more images and details.

Cheers
